// Generated by CoffeeScript 1.9.1
describe("First test", function() {
  return it("Should return true", function() {
    return expect(true).toBe(true);
  });
});

//# sourceMappingURL=MainSpec.js.map
